import Link from "next/link";
import { ArrowRight, Check, Star, ShieldCheck } from "lucide-react";
import * as Icons from "lucide-react";
import { reasons, services, site, testimonials, whatsappLink } from "@/data/site";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="mb-4 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.2em] text-blue-600"><span className="h-px w-7 bg-blue-600" />{children}</div>; }
export function SectionHeading({ eyebrow, title, text, centered=false }: { eyebrow:string; title:string; text?:string; centered?:boolean }) { return <div className={`${centered ? "mx-auto text-center" : ""} max-w-2xl`}><Eyebrow>{eyebrow}</Eyebrow><h2 className="text-3xl font-extrabold leading-tight tracking-[-.04em] text-[#101b36] md:text-5xl">{title}</h2>{text && <p className="mt-5 text-base leading-7 text-slate-500">{text}</p>}</div>; }
export function RatingBadge({ compact=false }: { compact?:boolean }) { return <div className={`inline-flex items-center gap-3 rounded-2xl border border-white/80 bg-white/75 px-4 py-3 shadow-xl shadow-blue-900/5 backdrop-blur ${compact ? "text-xs" : ""}`}><span className="grid size-9 place-items-center rounded-xl bg-[#fff2cc] text-[#d89b00]"><Star size={17} fill="currentColor" /></span><span><b className="block text-[#101b36]">4.9<span className="text-[#e5ad28]">★</span> Google Rating</b><small className="text-slate-500">94 reviews · established trust</small></span></div>; }
export function Stats() { return <div className="grid grid-cols-2 divide-x divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white p-1 shadow-sm sm:grid-cols-4 sm:divide-y-0"><div className="p-5"><b className="block text-2xl font-extrabold">4.9<span className="text-orange-400">★</span></b><span className="text-xs font-semibold text-slate-500">Google rating</span></div><div className="p-5"><b className="block text-2xl font-extrabold">94+</b><span className="text-xs font-semibold text-slate-500">reviews shared</span></div><div className="p-5"><b className="block text-2xl font-extrabold">1:1</b><span className="text-xs font-semibold text-slate-500">focused attention</span></div><div className="p-5"><b className="block text-2xl font-extrabold">100%</b><span className="text-xs font-semibold text-slate-500">personalized plans</span></div></div>; }
export function ServiceCard({ service }: { service: typeof services[number] }) { const Icon = (Icons as unknown as Record<string, React.ComponentType<{size?:number; className?:string}>>)[service.icon]; return <article className="group rounded-3xl border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-blue-200 hover:shadow-xl hover:shadow-blue-900/10"><div className="mb-6 flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-400 text-white shadow-lg shadow-blue-600/20`}><Icon size={22} /></span><ArrowRight size={19} className="text-slate-300 transition group-hover:translate-x-1 group-hover:text-blue-600" /></div><h3 className="text-lg font-bold">{service.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{service.description}</p><ul className="mt-5 grid gap-2">{service.benefits.map(benefit => <li key={benefit} className="flex items-center gap-2 text-xs font-semibold text-slate-600"><Check size={14} className="text-cyan-500" />{benefit}</li>)}</ul></article>; }
export function TestimonialCard({ item }: { item: typeof testimonials[number] }) { return <article className="rounded-3xl bg-white p-7 shadow-[0_14px_45px_rgba(16,27,54,.07)]"><div className="mb-5 flex items-center justify-between"><div className="flex gap-1 text-orange-400">{[1,2,3,4,5].map(star => <Star key={star} size={15} fill="currentColor" />)}</div><span className="text-xs font-bold text-slate-400">{item.role}</span></div><p className="text-[15px] leading-7 text-slate-600">“{item.quote}”</p><div className="mt-7 flex items-center gap-3 border-t border-slate-100 pt-5"><span className="grid size-10 place-items-center rounded-full bg-gradient-to-br from-indigo-100 to-cyan-100 text-sm font-bold text-blue-700">{item.name[0]}</span><div><b className="block text-sm">{item.name}</b><span className="text-xs text-slate-400">{item.subject}</span></div></div></article>; }
export function CTA() { return <section className="container py-20"><div className="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#315df6] via-[#554fd3] to-[#23b9b5] px-7 py-12 text-white md:px-16 md:py-16"><div className="absolute -right-16 -top-20 size-64 rounded-full border-[34px] border-white/10" /><div className="relative max-w-2xl"><ShieldCheck className="mb-6 text-cyan-200" size={31} /><h2 className="text-3xl font-extrabold leading-tight tracking-[-.04em] md:text-5xl">A better learning rhythm starts with one conversation.</h2><p className="mt-5 max-w-xl leading-7 text-blue-50">Tell us what your child needs. We’ll help you explore the right tutor, subject focus, and learning plan.</p><a href={`https://wa.me/${site.whatsapp}`} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-full bg-white px-6 py-3.5 text-sm font-extrabold text-[#315df6] transition hover:bg-cyan-50">Book a Free Demo Class <ArrowRight size={17} /></a></div></div></section>; }
export function PageIntro({ eyebrow, title, text }: {eyebrow:string; title:string; text:string}) { return <section className="mesh grid-lines"><div className="container py-20 md:py-28"><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-4xl text-4xl font-extrabold leading-[1.05] tracking-[-.05em] md:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{text}</p></div></section>; }
